### PR TITLE
Fix for PHP 7

### PR DESCRIPTION
**Pull request by Danone89**
I fixed dynamic calls in admin.class.php, new version of php need brakets, for correct return of values for this type of calls:
`$this->$foo` become `$this->{$foo}`

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Good fixes, thanks for the PR! I wrote this plugin many years ago now so I'm surprised I wasn't already doing this by then 😮 :)

**Comment by sc0ttkclark** [comment]
Heads up, not sure when this will go out to wordpress.org, I will see if there's anything else that's pending that needs to go out with this.

**Comment by Danone89** [comment]
I have some other minor fixes.
But they could break compability of existing setups. I will send you a pm
and push them to my fork.

Pozdrawiam
Daniel Bośnjak

2018-03-23 15:22 GMT+01:00 Scott Kingsley Clark <notifications@github.com>:

**Comment by sc0ttkclark** [comment]
Sounds great, thanks!

**Pull request merged**
